### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by dusta** [ayeo/gs1#1]
This is probably a mistake
class MyCustomCompany extends CompanyInterface

change to
class MyCustomCompany implements CompanyInterface

**Comment by ayeo** [comment]
Thank you, fixed (assumed you meant the readme file)

**Comment by dusta** [comment]
```
public function getName()
{
   return "My Custom Name"
}
```

missing ";"

**Comment by ayeo** [comment]
Fixed, thanks

**Comment by dusta** [comment]
class MyCustomLocation implements \Ayeo\Gs1\Standard\LocationInterface

``` php
Fatal error: Class Dframe\MyCustomLocation contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
```

**Comment by ayeo** [comment]
@dusta you probably has method with no body in your own class ;)

**Comment by dusta** [comment]
I know, but you have in interface and dont have in README.md :) 
I thought you'd guess

**Comment by ayeo** [comment]
ok, now I get it :) Will fix it, tnx again
