### ISSUE TITLE
Wrong barcode

### ISSUE THREAD

**Issue by dusta** [ayeo/gs1#2]
When generating a barcode is incorrect
 [barcode] => (01)(37)1(400)000001(15)(3301)(10)(00)012345600000000012

also for what is MyCustomLocation() ?

**Comment by ayeo** [comment]
GS1 assigns specific number to the company (GCP). Company may have many locations (address). Each location has own custom unique (in the Company) number (GLN). Ussusaly each location gets succeeding number starts from 00.

Could you provide more details about the problem?

**Comment by dusta** [comment]
@ayeo my mistake, I not completed the all the data

**Comment by dusta** [comment]
class MyCustomLocation implements \Ayeo\Gs1\Standard\LocationInterface

```php
Fatal error: Class Dframe\MyCustomLocation contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
